---
title: "PF-0953 Programación geoespacial en R<br>Tarea 04: flexdashboard"
author: "Manuel Vargas"
date: "2020-11-11"
output:
  html_document:
    theme: readable    
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: false  
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Descripción general
En esta tarea, desarrollará un tablero de control mediante el paquete [flexdashboard](https://rmarkdown.rstudio.com/flexdashboard/). El resultado final será un documento en la sintaxis [R Markdown](https://rmarkdown.rstudio.com/) publicado en [GitHub Pages](https://pages.github.com/).

## Fecha de entrega y entregables
La fecha límite de entrega es el **miércoles 18 de noviembre de 2020 antes de las 5:00 p.m. NO SE ACEPTARÁN ENTREGAS DESPUÉS DE ESA FECHA Y HORA.** Debe enviarle al profesor por correo electrónico la dirección del sitio en GitHub Pages resultante.

El proyecto puede realizarse en grupos de un máximo de tres estudiantes. Por favor copie el mensaje de correo a las direcciones de todos los integrantes del grupo e incluya los nombres de los integrantes en los metadatos del documento. Debe enviarse solamente un mensaje por grupo.

## Trabajo previo
Se recomienda leer el material preparado por el profesor para las lecciones y consultar la documentación y tutoriales de los paquetes de R que se utilizarán.

## Desarrollo
Complete el tablero de control sobre casos de COVID-19 en Costa Rica disponible en [https://pf0953-programaciongeoespacialr-2020.github.io/tablero-control-covid19-cr/](https://pf0953-programaciongeoespacialr-2020.github.io/tablero-control-covid19-cr/) y con código fuente en [https://github.com/pf0953-programaciongeoespacialr-2020/tablero-control-covid19-cr](https://github.com/pf0953-programaciongeoespacialr-2020/tablero-control-covid19-cr), de la siguiente manera:

1. (10%) Cambie los íconos de la página "Resumen" de manera que sean representativos de la cifra en cada *valueBox* (casos positivos, hospitalizados en salón, hospitalizados en UCI, etc.). Puede elegir los íconos de sitios como [Font Awsome](https://fontawesome.com/icons?d=gallery).
2. (30%) Complete la página de casos activos.
3. (30%) Complete la página de casos recuperados.
4. (30%) Complete la página de casos fallecidos.

Para los puntos 2, 3 y 4 cada página debe incluir:

a. (10%) Un *valueBox* con la cantidad de casos y el ícono correspondiente.  
b. (10%) Un mapa de coropletas que muestre la cantidad de casos en cantones.  
c. (10%) Un gráfico de barras que muestre los 10 cantones con más casos.  

Procure que los mapas, gráficos y demás componentes del tablero de control sean agradables a la vista y comuniquen apropiadamente la información que muestran.


